### ISSUE TITLE
Feature Request: add `lasagna` recipe

### ISSUE THREAD

**Issue by kael-k** [Depau/ricette.depau.eu#1]
## The issue
This repo lacks of a `lasagna` recipe

## Proposed fix
Add a `lasagna` recipe, if you don't have one yet I can make a PR for you

cc: @cifred98

**Comment by kael-k** [comment]
I am joking, writing a PR for a joke is way too much effort

**Comment by Depau** [comment]
![image](https://user-images.githubusercontent.com/1151321/192249755-609c116e-3e66-474e-b027-546f7c65b051.png)
